"""empty message

Revision ID: 3da9d79e1a82
Revises: 98a198a69927
Create Date: 2024-04-16 18:48:30.947505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3da9d79e1a82'
down_revision: Union[str, None] = '98a198a69927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('sip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('collection', sa.Column('dip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'dip')
    op.drop_column('collection', 'sip')
    # ### end Alembic commands ###
