"""empty message

Revision ID: 58151073f4a6
Revises: bcfd0263ab8f
Create Date: 2024-04-24 19:42:04.513129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58151073f4a6'
down_revision: Union[str, None] = 'bcfd0263ab8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectionpaperless',
    sa.Column('paperless_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('paperless_id')
    )
    op.create_index(op.f('ix_collectionpaperless_collection_id'), 'collectionpaperless', ['collection_id'], unique=False)
    op.create_table('documentpaperless',
    sa.Column('paperless_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('paperless_id')
    )
    op.create_index(op.f('ix_documentpaperless_doc_id'), 'documentpaperless', ['doc_id'], unique=False)
    op.create_table('userpaperless',
    sa.Column('paperless_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('paperless_id')
    )
    op.create_index(op.f('ix_userpaperless_user_id'), 'userpaperless', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpaperless_user_id'), table_name='userpaperless')
    op.drop_table('userpaperless')
    op.drop_index(op.f('ix_documentpaperless_doc_id'), table_name='documentpaperless')
    op.drop_table('documentpaperless')
    op.drop_index(op.f('ix_collectionpaperless_collection_id'), table_name='collectionpaperless')
    op.drop_table('collectionpaperless')
    # ### end Alembic commands ###
