"""empty message

Revision ID: a6d04b7953ac
Revises: 3caf248a3e4f
Create Date: 2024-05-02 19:10:42.057649

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6d04b7953ac"
down_revision: Union[str, None] = "3caf248a3e4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collectionpermission", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creator_id", sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.create_foreign_key("creator_id_fk", "user", ["creator_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collectionpermission", schema=None) as batch_op:
        batch_op.drop_constraint("creator_id_fk", type_="foreignkey")
        batch_op.drop_column("creator_id")

    # ### end Alembic commands ###
