"""empty message

Revision ID: b258395f0280
Revises: df3e00fa43c2
Create Date: 2024-05-23 16:42:00.335105

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b258395f0280"
down_revision: Union[str, None] = "df3e00fa43c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("manifest", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column("manifest_hash")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("manifest_hash", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("manifest")

    # ### end Alembic commands ###
