"""empty message

Revision ID: bcfd0263ab8f
Revises: 3da9d79e1a82
Create Date: 2024-04-23 19:03:38.284202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcfd0263ab8f'
down_revision: Union[str, None] = '3da9d79e1a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'sip')
    op.drop_column('collection', 'dip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('dip', sa.VARCHAR(), nullable=True))
    op.add_column('collection', sa.Column('sip', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
