"""empty message

Revision ID: df3e00fa43c2
Revises: a6d04b7953ac
Create Date: 2024-05-08 20:18:32.042959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df3e00fa43c2'
down_revision: Union[str, None] = 'a6d04b7953ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('manifest_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('share_state')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_state', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('manifest_hash')
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
